#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14

# Run from the dt-cli repository root; non-secret answers are remembered for re-runs.
cd "$(dirname "$0")/.."
ENV_FILE=".scratch/cli-governed-system-access/stg-acceptance.env"
EVIDENCE="docs/acceptance/evidence/governed-01-stg.json"
STG="https://gateway-stg.datousoft.com"
IAM_API="$STG/dt/iam"
PROFILE="supply-stg"
SYSTEM="supply-chain-server"
READ_OP="supply-chain-server.order-config.read"
SHOPS_OP="supply-chain-server.shops.list"
BATCH_OP="supply-chain-server.order-config.batch.read"
IAM_FIX_COMMIT="d661d61"   # orderMethod fix; the deployed IAM must contain it
SECRET_CLIPBOARD=false
cleanup_secrets() {
  if [[ "$SECRET_CLIPBOARD" == true ]]; then clear_clipboard; fi
  unset HMAC_SECRET IAM_PORTAL_TOKEN
}
trap cleanup_secrets EXIT
mkdir -p "$(dirname "$ENV_FILE")" "$(dirname "$EVIDENCE")"

now() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# ask_or KEY "Prompt" DEFAULT: like ask, with a first-run default.
ask_or() {
  local key="$1" prompt="$2" fallback="$3"
  if ! _existing "$key" >/dev/null 2>&1; then prompt="$prompt ${DIM}[Enter = ${fallback:-空}]${RESET}"; fi
  ask "$key" "$prompt"
  if [[ -z "${!key}" ]]; then printf -v "$key" '%s' "$fallback"; fi
  return 0
}

# record KEY VALUE [json]: upserts a non-sensitive value into the evidence file.
record() {
  python3 - "$EVIDENCE" "$1" "$2" "${3:-}" <<'PY'
import json, os, sys
path, key, value, kind = sys.argv[1:5]
data = json.load(open(path, encoding="utf-8")) if os.path.exists(path) else {}
node = data
*parents, leaf = key.split(".")
for part in parents:
    node = node.setdefault(part, {})
node[leaf] = (json.loads(value) if value else None) if kind == "json" else value
with open(path, "w", encoding="utf-8") as out:
    json.dump(data, out, ensure_ascii=False, indent=2)
    out.write("\n")
PY
}

# cli ARGS...: runs the release dt-cli; sets CLI_OUT (JSON envelope) and CLI_EXIT.
cli() {
  set +e
  CLI_OUT=$("$DTCLI" "$@")
  CLI_EXIT=$?
  set -e
}

# jfield dotted.path: a field of CLI_OUT (numbers index arrays); JSON for objects/lists/bools.
jfield() {
  printf '%s' "$CLI_OUT" | python3 -c '
import json, sys
try:
    v = json.load(sys.stdin)
except Exception:
    print(""); sys.exit(0)
for part in sys.argv[1].split("."):
    if isinstance(v, list) and part.isdigit():
        v = v[int(part)] if int(part) < len(v) else None
    elif isinstance(v, dict):
        v = v.get(part)
    else:
        v = None
    if v is None:
        break
if v is None:
    print("")
elif isinstance(v, (dict, list, bool)):
    print(json.dumps(v, ensure_ascii=False))
else:
    print(v)
' "$1"
}

# jcount dotted.path: length of a list field of CLI_OUT (0 when absent).
jcount() {
  printf '%s' "$(jfield "$1")" | python3 -c 'import json,sys
try: print(len(json.load(sys.stdin)))
except Exception: print(0)'
}

# to_clipboard TEXT: copies without printing; fails when no clipboard tool exists.
to_clipboard() {
  if command -v pbcopy >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v wl-copy >/dev/null 2>&1; then printf '%s' "$1" | wl-copy
  elif command -v xclip >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  else return 1; fi
}
clear_clipboard() {
  to_clipboard "" >/dev/null 2>&1 || true
  SECRET_CLIPBOARD=false
}

# hand_over_config LABEL YAML: masked preview on screen, the real block in the clipboard.
hand_over_config() {
  printf '%s\n' "$2" | sed -E 's/(secret: ).*/\1"<剪贴板中的共享密钥>"/' | sed 's/^/      /'
  if to_clipboard "$2"; then
    SECRET_CLIPBOARD=true
    note "完整内容（含密钥）已在剪贴板，直接粘贴。"
  else
    warn "没有可用的剪贴板工具；请先配置剪贴板工具后重跑，密钥不会输出到终端。"
    return 1
  fi
}

# governed_probe: status of a well-formed authorize request (503 off/not ready, 403 on but
# not registered or denied, 302 on and registered). It creates no authorization.
governed_probe() {
  local state challenge
  state=$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')
  challenge=$(python3 -c 'import secrets,hashlib,base64; v=secrets.token_urlsafe(48); print(base64.urlsafe_b64encode(hashlib.sha256(v.encode()).digest()).decode().rstrip("="))')
  curl -s -m 15 -o /dev/null -w '%{http_code}' \
    "$IAM_API/cli-api/oauth2/authorize?client_id=dt-cli&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A18765%2Foauth%2Fcallback&state=$state&code_challenge=$challenge&code_challenge_method=S256&systemId=$SYSTEM&environment=stg" || echo 000
}
iam_deployed_sha() {
  curl -s -m 15 "$IAM_API/actuator/info" | python3 -c 'import json,sys
try: print(json.load(sys.stdin)["git"]["commit"]["id"])
except Exception: print("")' || true
}
iam_has_fix() {
  local sha="$1"
  [[ -n "$sha" ]] && git -C "$IAM_REPO" merge-base --is-ancestor "$IAM_FIX_COMMIT" "$sha" 2>/dev/null
}
auth_endpoint_status() {
  curl -s -m 15 -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' -d '{}' \
    "$AUTH_BASE/internal/cli-api/v1/credentials" || echo 000
}
# ga ARGS...: the dt-iam admin helper with the portal token only in its own environment.
ga() {
  IAM_PORTAL_TOKEN="$IAM_PORTAL_TOKEN" python3 "$IAM_REPO/scripts/governed-admin.py" --api "$IAM_API" --origin "$STG" "$@"
}

banner "受控访问票 01：STG 开通与验收取证"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "预检：工具、仓库与 STG 当前版本"
say "检查本机工具和 dt-iam 仓库，编译发行版 dt-cli，并读取 STG 上 IAM 的部署版本。"
for tool in curl python3 git cargo openssl; do
  command -v "$tool" >/dev/null 2>&1 || { warn "缺少 $tool，先安装后重跑。"; exit 1; }
done
ask_or IAM_REPO "dt-iam 仓库路径:" "$HOME/IdeaProjects/dt-iam-codex-dtcli"
if [[ ! -f "$IAM_REPO/scripts/governed-admin.py" || ! -f "$IAM_REPO/sql/20260924_governed_cli_access.sql" ]]; then
  warn "该路径下没有 scripts/governed-admin.py 或迁移 SQL（需要 codex/dt-cli ≥ $IAM_FIX_COMMIT）。"; exit 1
fi
write_env IAM_REPO "$IAM_REPO"
ask EXECUTOR "执行人（写入证据的姓名，不要填账号）:"
write_env EXECUTOR "$EXECUTOR"
note "编译 dt-cli 发行版（约 1 分钟）…"
cargo build --release --locked --quiet
DTCLI="$PWD/target/release/dt-cli"
cli version
[[ "$CLI_EXIT" == 0 ]] || { warn "dt-cli version 失败。"; exit 1; }
# Each run gets fresh evidence. Preserve earlier runs without carrying forward old passes.
python3 - "$EVIDENCE" <<'PY'
from datetime import datetime, timezone
from pathlib import Path
import sys
path = Path(sys.argv[1])
if path.exists():
    stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')
    path.rename(path.with_name(f'{path.stem}-{stamp}{path.suffix}'))
path.write_text('{}\n', encoding='utf-8')
PY
record ticket "cli-governed-system-access/01"
record executor "$EXECUTOR"
record startedAt "$(now)"
record cli.version "$(jfield data.cliVersion)"
record cli.buildCommit "$(jfield data.buildCommit)"
git -C "$IAM_REPO" fetch -q origin stg codex/dt-cli || warn "dt-iam fetch 失败，版本比对可能不准。"
IAM_SHA=$(iam_deployed_sha)
say "STG 上 IAM 当前部署：${IAM_SHA:-读取失败}"
if iam_has_fix "$IAM_SHA"; then note "已包含 orderMethod 修正 $IAM_FIX_COMMIT。"
else warn "尚未包含 $IAM_FIX_COMMIT（IAM stg 需部署到 0a014fc 或更新）；第 3 阶段会再确认。"; fi
record iam.deployedShaAtStart "$IAM_SHA"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "AUTH：写入受控访问配置（共享 HMAC 密钥）"
say "IAM 用这个密钥签名换证请求，AUTH 用它验签；两边必须完全相同。"
say "密钥只放进剪贴板，不打印、不写文件。AUTH 只在启动时读取这组配置。"
if confirm "生成新的共享密钥？（首次选 y；AUTH 已配置过则选 N 并粘贴原密钥）"; then
  HMAC_SECRET=$(openssl rand -base64 48 | tr '+/' '-_' | tr -d '=\n')
else
  ask_secret HMAC_SECRET "粘贴 AUTH 已配置的 auth.cli-api.hmac-secret:"
fi
if (( ${#HMAC_SECRET} < 32 )); then warn "密钥不足 32 字节。"; exit 1; fi
ask NACOS_URL "Nacos 控制台地址:"
write_env NACOS_URL "$NACOS_URL"
open_url "$NACOS_URL"
step "命名空间 public → 配置管理 → 打开 AUTH 的主配置（通常 dataId auth-core-stg.yml、分组 stg；以现有 jwt/redis 配置所在者为准）。"
step "把下面这段并入配置；若已有顶层 auth: 键，把 cli-api 块放到它下面，不要写第二个 auth:。"
hand_over_config "AUTH" "$(printf 'auth:\n  cli-api:\n    enabled: true\n    environment: stg\n    hmac-secret: "%s"\n' "$HMAC_SECRET")"
pause "发布 AUTH 配置后按 Enter"
clear_clipboard
record auth.configuredAt "$(now)"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "部署 AUTH stg，并确认两端都已上线"
say "AUTH 的 stg 已推送合并提交 6dbdd8d0，但 STG 仍是旧版本；部署后才会读取上一步的配置。"
ask PIPELINE_URL "AUTH stg 部署流水线地址（云效 Flow）:"
write_env PIPELINE_URL "$PIPELINE_URL"
open_url "$PIPELINE_URL"
step "运行 stg 分支流水线（提交应为 6dbdd8d0 或更新），等部署完成。"
pause "部署完成后按 Enter 开始探测"
ask_or AUTH_BASE "AUTH 的 HTTPS 基址（IAM 调用它换证）:" "$STG/authority"
write_env AUTH_BASE "$AUTH_BASE"
code=000
for _ in $(seq 1 60); do
  code=$(auth_endpoint_status)
  [[ "$code" == 403 ]] && break
  printf '.'; sleep 10
done
printf '\n'
if [[ "$code" == 403 ]]; then note "AUTH 新入口在线：未签名请求被拒（403）。"
else warn "AUTH 新入口仍返回 $code（404 表示仍是旧版本）；确认部署后重跑本向导。"; exit 1; fi
ask AUTH_DEPLOYED_SHA "流水线上显示的 AUTH 部署提交:"
record auth.deployedSha "$AUTH_DEPLOYED_SHA"
record auth.unsignedCredentialStatus "$code"
record auth.checkedAt "$(now)"
note "IAM stg 推送后会自动部署；等待其包含 $IAM_FIX_COMMIT …"
for _ in $(seq 1 60); do
  IAM_SHA=$(iam_deployed_sha)
  iam_has_fix "$IAM_SHA" && break
  printf '.'; sleep 10
done
printf '\n'
if iam_has_fix "$IAM_SHA"; then note "IAM 已部署 $IAM_SHA。"
else warn "IAM 仍为 ${IAM_SHA:-未知}；在 IAM 流水线部署 stg 后重跑。"; exit 1; fi
record iam.deployedSha "$IAM_SHA"
record iam.checkedAt "$(now)"
note "建议另请运维限制公网网关对 /authority/internal/** 的访问（接口已要求 IAM 签名，这是纵深防御）。"
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "IAM：执行受控访问迁移（只增表）"
say "在 IAM 的 STG 权威库（与 cli_authorization、cli_launch_delivery 同库）执行："
say "  $IAM_REPO/sql/20260924_governed_cli_access.sql"
note "全部是新增表；回滚应用时也要保留。表已存在说明执行过，不要删表重建。"
if confirm "现在由你在数据库客户端执行这份迁移？（写库操作）"; then
  if to_clipboard "$(cat "$IAM_REPO/sql/20260924_governed_cli_access.sql")"; then note "SQL 已复制到剪贴板。"; fi
  pause "执行成功后按 Enter"
  record migration.appliedAt "$(now)"
  record migration.appliedBy "$EXECUTOR"
else
  warn "未执行迁移：下一阶段开启模块后，探针会一直是 503。"
fi

# ── 5 ────────────────────────────────────────────────────────────────────
stage "IAM：开启模块并配置 Nacos 服务绑定"
say "iam.governed.* 随 Nacos 发布自动生效，无需重启 IAM。"
ask_or SUPPLY_SERVICE_ID "IAM 直连供应链的 Nacos 服务名:" "supply-chain-server"
ask_or SUPPLY_INTERNAL_PREFIX "供应链服务内路径前缀（Gateway 已去掉 /supply-chain-server）:" ""
step "确认 Nacos public 命名空间、stg 分组能发现供应链服务且有健康实例。"
ask_or MANAGER_ROLE_IDS "可维护受控访问的现有管理角色 ID（逗号分隔；只用超级管理员就留空）:" ""
for key in SUPPLY_SERVICE_ID SUPPLY_INTERNAL_PREFIX MANAGER_ROLE_IDS; do write_env "$key" "${!key}"; done
ROLES_YAML=$(printf '%s' "$MANAGER_ROLE_IDS" | tr -d ' ' | sed 's/,/, /g')
open_url "$NACOS_URL"
step "命名空间 public、分组 stg，打开 IAM 主配置（dt-iam.yaml 或 dt-iam-stg.yaml，与现有 iam.cli 同一个 dataId），并入顶层 iam: 下："
hand_over_config "IAM" "$(cat <<YAML
iam:
  governed:
    enabled: true
    environment: stg
    api-origin: $IAM_API
    portal-origin: $STG
    auth-base-uri: $AUTH_BASE
    auth-hmac-secret: "$HMAC_SECRET"
    manager-role-ids: [$ROLES_YAML]
    bindings:
      supply-stg:
        service-id: $SUPPLY_SERVICE_ID
        path-prefix: "$SUPPLY_INTERNAL_PREFIX"
YAML
)"
pause "发布 IAM 配置后按 Enter"
clear_clipboard
unset HMAC_SECRET
probe=000
for _ in $(seq 1 30); do
  probe=$(governed_probe)
  [[ "$probe" == 403 || "$probe" == 302 ]] && break
  printf '.'; sleep 5
done
printf '\n'
case "$probe" in
  403|302) note "模块已开启（授权入口 $probe）。" ;;
  *) warn "授权入口仍为 $probe：503 表示配置未生效、格式不合规或迁移未执行。"; exit 1 ;;
esac
record config.iamEnabledAt "$(now)"
record config.authorizeProbeStatus "$probe"
record config.binding.serviceId "$SUPPLY_SERVICE_ID"
record config.binding.pathPrefix "$SUPPLY_INTERNAL_PREFIX"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "管理员：登记供应链、发布三条操作并授权"
say "用你自己的 IAM 门户 token 调管理 API；token 只在子进程环境中使用，不保存。"
ask IAM_CONSOLE_URL "IAM 管理后台地址:"
write_env IAM_CONSOLE_URL "$IAM_CONSOLE_URL"
open_url "$IAM_CONSOLE_URL"
step "登录后打开开发者工具 → Network，点任一 /dt/iam 请求 → Request Headers → Authorization，复制 Bearer 后面的值。"
ask_secret IAM_PORTAL_TOKEN "粘贴门户 token:"
if ! systems=$(ga systems); then exit 1; fi
if printf '%s' "$systems" | python3 -c 'import json,sys; sys.exit(0 if any(r["system_id"]=="supply-chain-server" and r["environment"]=="stg" for r in json.load(sys.stdin)) else 1)'; then
  note "supply-chain-server/stg 已登记。"
else
  ga register-system --system "$SYSTEM" --environment stg --binding supply-stg >/dev/null
  note "已登记 supply-chain-server/stg。"
fi
for op in "$READ_OP" "$SHOPS_OP" "$BATCH_OP"; do
  state=$(ga operations --system "$SYSTEM" --environment stg | python3 -c 'import json,sys
op=sys.argv[1]
print(next((r["state"] for r in json.load(sys.stdin) if r["operation_id"]==op and r["operation_version"]=="1.0.0"), ""))' "$op")
  if [[ -z "$state" ]]; then ga publish --system "$SYSTEM" --environment stg --operation "$op" >/dev/null; state=PUBLISHED; fi
  [[ "$state" == PUBLISHED ]] || { warn "$op@1.0.0 当前为 $state，需要人工处理后重跑。"; exit 1; }
  note "$op@1.0.0 已发布。"
done
operations=$(ga operations --system "$SYSTEM" --environment stg)
for op in "$READ_OP" "$SHOPS_OP" "$BATCH_OP"; do
  digest=$(printf '%s' "$operations" | python3 -c 'import json,sys
op=sys.argv[1]
print(next(r["contract_digest"] for r in json.load(sys.stdin) if r["operation_id"]==op and r["operation_version"]=="1.0.0"))' "$op")
  record "registration.digests.$op" "$digest"
done
if confirm "试点员工就是你本人（管理员自授权）？"; then
  who=(--self)
else
  ask PILOT_USER_ID "试点员工的 IAM 用户 ID:"
  who=(--user "$PILOT_USER_ID")
fi
if confirm "为试点员工授予三条操作 7 天 Grant？（已有有效 Grant 可选 N 跳过）"; then
  for op in "$READ_OP" "$SHOPS_OP" "$BATCH_OP"; do
    ga grant "${who[@]}" --system "$SYSTEM" --environment stg --operation "$op" --days 7 >/dev/null
    note "已授权 $op。"
  done
  record registration.grantedAt "$(now)"
fi
unset IAM_PORTAL_TOKEN
record registration.by "$EXECUTOR"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "试点员工：本人登录 dt-cli"
say "dt-cli 会打开 IAM 同意页：用本人 IAM 账号登录，勾选三条供应链操作（1.0.0）后同意。"
note "登录必须在这个交互终端完成；浏览器回调后 dt-cli 会自动继续。"
cli auth login --profile "$PROFILE" --environment stg --system "$SYSTEM"
if [[ "$CLI_EXIT" != 0 ]]; then
  warn "登录失败：$(jfield error.code) trace=$(jfield meta.traceId)"; exit 1
fi
record login.at "$(now)"
record login.authorizationExpiresAt "$(jfield data.authorizationExpiresAt)"
cli catalog sync --profile "$PROFILE"
[[ "$CLI_EXIT" == 0 ]] || { warn "目录同步失败：$(jfield error.code)"; exit 1; }
record catalog.operationCount "$(jfield data.operationCount)"
record catalog.revision "$(jfield data.catalogRevision)"
note "登录与目录同步完成（授权至 $(jfield data.authorizationExpiresAt)）。"
pause

# ── 8 ────────────────────────────────────────────────────────────────────
stage "供应链门户：记录会话基线（A4）"
say "受控查询期间，你原来的供应链门户会话和当前配送中心视图都必须保持不变。"
ask BOH_URL "供应链门户（BOH）地址:"
write_env BOH_URL "$BOH_URL"
open_url "$BOH_URL"
step "确认已登录，且当前视图是配送中心；保持这个标签页，稍后回来复核。"
ask PORTAL_VIEW_BEFORE "当前配送中心（名称或 ID，不要写账号）:"
record portal.viewBefore "$PORTAL_VIEW_BEFORE"
record portal.baselineAt "$(now)"

# ── 9 ────────────────────────────────────────────────────────────────────
stage "真实查询：2021003 × 101010009 订货配置（A6）"
say "预期 minOrderNum 为 \"1\"；不一致会如实记录为失败，不调整预期。"
cli api call "$READ_OP" --profile "$PROFILE" --params '{"shopCode":"2021003","itemCode":"101010009"}'
record singleStore.at "$(now)"
record singleStore.exit "$CLI_EXIT"
record singleStore.traceId "$(jfield meta.traceId)"
record singleStore.expectedMinOrderNum "1"
if [[ "$CLI_EXIT" == 0 ]]; then
  min=$(jfield data.items.0.minOrderNum)
  record singleStore.itemCount "$(jcount data.items)" json
  record singleStore.firstItem "$(jfield data.items.0)" json
  record singleStore.contractDigest "$(jfield meta.contractDigest)"
  record singleStore.complete "$(jfield meta.complete)" json
  if [[ "$min" == "1" ]]; then
    record singleStore.pass true json; note "通过：minOrderNum = \"1\"。"
  else
    record singleStore.pass false json; warn "与预期不一致：minOrderNum = \"${min:-空}\"（已记录为失败）。"
  fi
else
  record singleStore.pass false json
  record singleStore.errorCode "$(jfield error.code)"
  warn "查询失败：$(jfield error.code)（trace $(jfield meta.traceId)）；已记录为失败。"
fi
pause

# ── 10 ───────────────────────────────────────────────────────────────────
stage "非授权门店：必须拒绝且不返回数据（A3）"
say "填一个你当前无权访问的门店编码（例如其他配送中心的门店）。"
ask FOREIGN_SHOP "无权门店编码:"
write_env FOREIGN_SHOP "$FOREIGN_SHOP"
cli api call "$READ_OP" --profile "$PROFILE" --params "{\"shopCode\":\"$FOREIGN_SHOP\",\"itemCode\":\"101010009\"}"
record foreignStore.shopCode "$FOREIGN_SHOP"
record foreignStore.exit "$CLI_EXIT"
record foreignStore.errorCode "$(jfield error.code)"
record foreignStore.traceId "$(jfield meta.traceId)"
record foreignStore.at "$(now)"
if [[ "$CLI_EXIT" == 4 && "$(jfield error.code)" == DATA_SCOPE_DENIED && -z "$(jfield data)" ]]; then
  record foreignStore.pass true json; note "通过：DATA_SCOPE_DENIED，无数据。"
else
  record foreignStore.pass false json; warn "未按预期拒绝：退出码 $CLI_EXIT，$(jfield error.code)。"
fi
pause

# ── 11 ───────────────────────────────────────────────────────────────────
stage "有权门店与大区批量（A6 批量）"
cli api call "$SHOPS_OP" --profile "$PROFILE" --params '{}'
record shops.exit "$CLI_EXIT"
record shops.traceId "$(jfield meta.traceId)"
record shops.firstPageComplete "$(jfield meta.complete)" json
record shops.firstPageCount "$(jcount data.items)" json
say "本人有权门店（第一页）：$(jcount data.items) 家"
ask_or BATCH_PARTITION "可选：限定分区 locatedPartitionId（留空=当前全部可见门店）:" ""
write_env BATCH_PARTITION "$BATCH_PARTITION"
params='{"itemCode":"101010009"}'
[[ -n "$BATCH_PARTITION" ]] && params="{\"itemCode\":\"101010009\",\"locatedPartitionId\":$BATCH_PARTITION}"
cli jobs submit "$BATCH_OP" --profile "$PROFILE" --params "$params"
[[ "$CLI_EXIT" == 0 ]] || { warn "提交失败：$(jfield error.code)"; record batch.submitError "$(jfield error.code)"; exit 1; }
JOB=$(jfield data.jobId)
record batch.jobId "$JOB"
record batch.submittedAt "$(now)"
record batch.params "$params" json
state=queued
for _ in $(seq 1 130); do
  cli jobs status "$JOB" --profile "$PROFILE"
  state=$(jfield data.state)
  [[ "$state" != queued && "$state" != running ]] && break
  printf '.'; sleep 5
done
printf '\n'
record batch.state "$state"
record batch.failureCode "$(jfield data.failureCode)"
record batch.pageCount "$(jfield data.pageCount)"
if [[ "$state" == succeeded ]]; then
  cli jobs result "$JOB" --profile "$PROFILE"
  record batch.resultExit "$CLI_EXIT"
  record batch.complete "$(jfield data.complete)" json
  record batch.shopCount "$(jfield data.shopCount)"
  record batch.itemCount "$(jfield data.itemCount)"
  record batch.traceId "$(jfield meta.traceId)"
  note "批量完成：$(jfield data.shopCount) 家门店、$(jfield data.itemCount) 条配置，complete=$(jfield data.complete)。"
else
  warn "批量结束于 $state（$(jfield data.failureCode)）；已记录，不作为完整结果。"
fi
pause

# ── 12 ───────────────────────────────────────────────────────────────────
stage "供应链门户：复核会话与视图（A4）"
open_url "$BOH_URL"
step "回到门户标签页刷新，打开任一需要登录的页面，看是否仍在登录状态。"
if confirm "门户仍保持登录、没有被踢出？"; then record portal.sessionKept true json
else record portal.sessionKept false json; warn "已记录：门户会话受影响。"; fi
ask PORTAL_VIEW_AFTER "当前配送中心（名称或 ID）:"
record portal.viewAfter "$PORTAL_VIEW_AFTER"
if [[ "$PORTAL_VIEW_AFTER" == "$PORTAL_VIEW_BEFORE" ]]; then record portal.viewUnchanged true json
else record portal.viewUnchanged false json; warn "视图与基线不同，已记录。"; fi
record portal.checkedAt "$(now)"

# ── 13 ───────────────────────────────────────────────────────────────────
stage "注销：远端撤销与本地清理（A5）"
cli auth logout --profile "$PROFILE"
record logout.exit "$CLI_EXIT"
record logout.remoteRevocation "$(jfield data.remoteRevocation)"
record logout.localCleanup "$(jfield data.localCleanup)"
record logout.at "$(now)"
cli api call "$READ_OP" --profile "$PROFILE" --params '{"shopCode":"2021003","itemCode":"101010009"}'
record logout.callAfterLogoutExit "$CLI_EXIT"
record logout.callAfterLogoutCode "$(jfield error.code)"
note "远端撤销：$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["logout"]["remoteRevocation"])' "$EVIDENCE")；注销后调用退出码 $CLI_EXIT。"
pause

# ── 14 ───────────────────────────────────────────────────────────────────
stage "汇总证据"
record finishedAt "$(now)"
python3 - "$EVIDENCE" <<'PY'
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
def mark(ok): return "通过" if ok is True else ("失败" if ok is False else "未执行")
rows = [
    ("A6 单店 2021003×101010009", mark(d.get("singleStore", {}).get("pass")), d.get("singleStore", {}).get("traceId")),
    ("A3 非授权门店拒绝", mark(d.get("foreignStore", {}).get("pass")), d.get("foreignStore", {}).get("traceId")),
    ("A6 批量完整结果", mark(d.get("batch", {}).get("complete")), d.get("batch", {}).get("traceId")),
    ("A4 门户会话保持", mark(d.get("portal", {}).get("sessionKept")), None),
    ("A4 配送中心视图不变", mark(d.get("portal", {}).get("viewUnchanged")), None),
    ("A5 远端撤销", "通过" if d.get("logout", {}).get("remoteRevocation") == "confirmed" else "失败", None),
]
print("  部署：IAM %s，AUTH %s" % (d.get("iam", {}).get("deployedSha"), d.get("auth", {}).get("deployedSha")))
for name, result, trace in rows:
    print("  %-22s %s%s" % (name, result, ("  trace=" + trace) if trace else ""))
PY
say ""
say "证据已写入 $EVIDENCE（只含版本、时间、traceId 与结果，不含凭证或账号）。"
warn "仍需另行完成：A7 基线 2 分钟 + 慢上游 2 分钟压测；A5 多实例 5 秒停用与回滚演练；为 GOVERNED_AUDIT_UNAVAILABLE 配 60 秒告警。"
pause "按 Enter 结束"

finish
